name: Publish to npm

on:
  # 当推送到特定分支时触发，比如 `main` 分支
  push:
    branches:
      - master
  # 当创建新的 Git 标签时触发
  tags:
    - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" # 使用 LTS 版本
          cache: "npm" # 缓存依赖

      # 配置 npm 的 authToken
      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 发布到 npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
